- name: configure sshuttle bastion host
  become: true
  hosts: bastion
  #gather_facts: false
  tasks:
    - name: ensure python3 is installed
      package:
        name: python3
        state: present

    - name: adjust MaxSessions
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MaxSessions'
        line: 'MaxSessions 50'
        state: present

    - name: adjust MaxStartups
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^MaxStartups'
        line: 'MaxStartups 50:30:80'
        state: present

    - name: restart sshd
      service:
        name: sshd
        state: restarted
