apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
    generateName: minio-push-and-pull-
spec:
    volumeClaimTemplates:
    - metadata:
        name: fetch-from-minio-pvc
      spec:
        storageClassName: local-storage
        accessModes: 
        - ReadWriteMany
        resources:
          requests:
            storage: 3Gi

    entrypoint: minio-sequence
    
    templates:
    - name: minio-sequence
      steps:
      - - name: upload-to-minio
          template: upload-to-minio

      - - name: sleep-for-5-seconds
          template: sleep-for-5-seconds

      - - name: fetch-from-minio
          template: fetch-from-minio

      - - name: repeat
          template: minio-sequence

    - name: upload-to-minio
      container:
        image: watcher00090/deployment-automation-playground-upload-to-minio
        env: 
        - name: MINIO_SERVER_AND_PORT
          value: '3.15.232.78:32477'
        - name: MINIO_ACCESS_KEY
          valueFrom: 
            secretKeyRef:
              name: minio-server-authentication-info
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom: 
            secretKeyRef:
              name: minio-server-authentication-info
              key: MINIO_SECRET_KEY

    - name: fetch-from-minio
      container: 
        image: watcher00090/deployment-automation-playground-fetch-from-minio
        env: 
        - name: MINIO_SERVER_AND_PORT
          value: '3.15.232.78:32477'
        - name: MINIO_ACCESS_KEY
          valueFrom: 
            secretKeyRef:
              name: minio-server-authentication-info
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom: 
            secretKeyRef:
              name: minio-server-authentication-info
              key: MINIO_SECRET_KEY
        volumeMounts:
        - name: fetch-from-minio-pvc
          mountPath: '/mnt/localpv-vol-0'

    
    - name: sleep-for-5-seconds      
      container:
        image: ubuntu
        command: [sleep]
        args: ["5s"]
