apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fetch-from-minio-pvc
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
