apiVersion: v1
kind: Pod
metadata:
    name: minio-pod
    labels:
        name: minio-pod
spec:
    containers:
    - name: minio-container
      image: minio/minio
      env: 
      - name: MINIO_ACCESS_KEY
        value: "HKJSDF98jkd76hjsDJKSDjk"
      - name: MINIO_SECRET_KEY
        value: "kd89jk3298sdkjHJKDSds89ds/87sd87*"
      command: ["minio"]
      args: ["server", "/data"]
      ports:
      - containerPort: 9000
    restartPolicy: OnFailure
